library(shiny)
library(rootSolve)

# setwd("~/Documents/GitHub/2020-ncov/stoch_model_shiny/")

# Define UI for slider demo application
shinyUI(fluidPage(
  
  #  Application title
  h3("Probability of a large 2019-nCoV outbreak following introduction of cases"),
  
  p(em("Note: this is preliminary analysis and has not been peer-reviewed.")),
  
  p("This analysis uses a model that incorporates randomness and individual-level variation in transmission
    (i.e. potential for 'superspreading') to calculate the probability that a given number of independently
    introduced cases in a new location will eventually lead to a large outbreak. (Source: Lloyd-Smith et al, Nature, 2005)."),

  p("There are two key values to explore: the reproduction number in the new location (i.e. average number of secondary cases
    generated by a typical infectious individual); and individual-level variation in transmission - do all cases generate similar numbers of secondary cases,
    or do most generate few and some lots?"),
  
  p("Infections with more individual-level variation (such as SARS) lead to more fragile initial transmission chains, 
    and hence are overall less likely to spark a large outbreak following an introduced case (although they can lead to rapidly growing outbreaks if by chance transmission 
    does take hold. The random-mixing option in the drop-down menu assumes transmission occurs at random with similar secondary cases from all individuals."),
  
  hr(),
  
  # Sidebar with sliders that demonstrate various available
  # options
  sidebarLayout(
    sidebarPanel(
      # Decimal interval with step value

      sliderInput("R0value", "Assumed local reproduction number (estimated range of 1.5-3 in Wuhan):", 
                  min = 1, max = 4, value = 2, step= 0.1),
      selectInput("k", 
                  label = "Assumed individual-level variation in transmission",
                  choices = list("SARS-like", "MERS-like",
                                 "Random-mixing","nCoV-like (early estimate)"),
                  selected = "SARS-like")

    ),
    
    # Show a table summarizing the values entered
    mainPanel(
      plotOutput('plot')
    )
  ),
  
  hr(),
  
  h4('Limitations'),
  
  p("Although the model includes randomness and individual-level variation in transmission, it is still only
    a simple representation of how transmission may occur initially: factors such as social structure and changes in behaviour may influence
    dynamics in ways that are not reflected here."),
  
  p("Values for individual-level variation in SARS and MERS-CoV are cited in Kucharski & Althaus (Eurosurveillance, 2015). However, 
    2019-nCoV may have a different value to these in reality."),

  h4('About this app'),
  
  p("Contributors: Adam Kucharski, Christian Althaus, Tim Russell, Charlie Diamond, CMMID nCoV working group, Sebastian Funk, Rosalind Eggo."),
  p("More real-time nCoV analysis by CMMID is ", a(href = 'https://cmmid.github.io/ncov','available here.')),
  
  h4('References'),
  
  p(a(href = "https://www.medrxiv.org/content/10.1101/2020.01.31.20019901v1","Kucharski AJ, Russell TW, Diamond C et al. Early dynamics of transmission and control of 2019-nCoV: a mathematical modelling study. MedRxiv, 2020")),
  p(a(href = "XX","Kucharski AJ, Althaus C.  The role of superspreading in Middle East respiratory syndrome coronavirus (MERS-CoV) transmission. Eurosurveillance, 2015")),
  
  hr()
  
))